name: invoicepro
description: Flutter invoice manager with GST, PDF generation and SQLite storage.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3
  path: ^1.9.0
  pdf: ^3.11.1
  printing: ^5.13.4
  share_plus: ^10.0.2
  intl: ^0.19.0
  cupertino_icons: ^1.0.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
